services:
  - type: web
    name: movieverse-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src/api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: true
